### ISSUE TITLE
Note at current line depends of git branch?

### ISSUE THREAD

**Issue by olejech** [RutaTang/quicknote.nvim#14]
If I switch to other branch — I can't see my notes at current line.
But if I switch back to previous branch — I will to see notes

How I can disable this behaviour?
Thanks for great plugin!

**Comment by RutaTang** [comment]
Hi olejech, 

Yes, this "git-branch-supported" feature was implemented in this #7 PR. 

And thank you for your issue. I will try to make it customizable.

**Comment by RutaTang** [comment]
After thinking around, since in `portable` mode, `notes` are all stored within your project under `.quicknote` folder rather than being stored in global and because each git branch may have very different content inside,  if I disable the "git-branch-supported" feature for `portable` mode, it may cause to a mess. 

Thus, a final thought from me for now is to allow users to disable the "git-branch-supported" feature in the `resident` model.

**Comment by RutaTang** [comment]
After this commit [feat: support git branch recognizable in resident mode](https://github.com/RutaTang/quicknote.nvim/commit/b84c7d5127c5861a9f40c7f130a00bceb4252150), it should work now, and the "git-branch-supported" feature is now only supported in `resident` mode which makes more sense.
